# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronovone', '0002_delete_blogarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_month='pubdate')),
                ('pubdate', models.DateField()),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
    ]
